version: '2.1'

services:
  mongo:
    image: mongo
    container_name: document-db
    restart: always
    ports:
      - "27017:27017"
  projects:
    image: aostreetart/aeselprojects:latest
    container_name: projects
    ports:
      - "5644:5644"
    environment:
      - MONGO_HOSTS=document-db
      - SPRING_CLOUD_CONSUL_HOST=registry
      - SPRING_CLOUD_CONSUL_DISCOVERY_PREFERIPADDRESS=true
